/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by pbtools.
 */

#include <limits.h>
#include "data.h"
// #include "nwy_test_cli_adpt.h"

#if CHAR_BIT != 8
#error "Number of bits in a char must be 8."
#endif

// extern uint8_t BleRxData[20];

// extern float unencoded_longitude;
// extern float unencoded_latitude;
// extern float unencoded_altitude;

void com_emotorad_backend_aggregation_flink_data_bike_init(
    struct com_emotorad_backend_aggregation_flink_data_bike_t *self_p,
    struct pbtools_heap_t *heap_p)
{
    self_p->base.heap_p = heap_p;
    self_p->vehicle_speed = 1;
    self_p->motor_speed = 20; // not in sample
    self_p->battery_voltage = 24063;
    self_p->soc = 36;
    self_p->throttle = 1861;
    self_p->throttle_cut_off = 1;
    self_p->pas = 2;
    self_p->eng_mode = 2;
    self_p->distance_to_empty = 12;
    self_p->calories = 257;
    self_p->current_trip_distance = 261.9656193149855;
    self_p->current_trip_max_speed = 20;
    self_p->child_mode_speed_limit = 20;
    self_p->side_stand = 1;
    self_p->headlamp = 1;
    self_p->brake = 1;
    self_p->cruise_control = 1;
    self_p->walk_mode = 1;
    self_p->vehicle_odo_reading = 10;
    self_p->motor_hall_failure = 1;
    self_p->motor_line_short_circuit_fault = 1;
    self_p->brake_failure = 1;
    self_p->handle_bar_failure = 1;
    self_p->battery_under_voltage_fault = 1;
    self_p->display_and_mcu_comm_failure = 1;
    self_p->overvoltage_fault = 1;
    self_p->controller_opamp_failure = 1;
    self_p->motor_stall_fault = 1;
    self_p->mcu_debug_signal0 = 4;
    self_p->mcu_debug_signal1 = 1;
    self_p->mcu_debug_signal2 = 1;
    self_p->mcu_debug_signal3 = 4;
    self_p->ble_debug_signal0 = 8;
    self_p->ble_debug_signal1 = 3;
    self_p->ble_debug_signal2 = 6;
    self_p->ble_debug_signal3 = 8;
    self_p->emuser_id_p = "0b927d97-782a-4c82-b9d2-e4e06774ed37";
    self_p->vin_p = "Indian User";
    self_p->latitude = 13.9210121;
    self_p->longitude = 77.6722252;
    self_p->altitude = 10;
    self_p->time = 1720071401563;
}

void com_emotorad_backend_aggregation_flink_data_bike_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct com_emotorad_backend_aggregation_flink_data_bike_t *self_p)
{
    pbtools_encoder_write_uint64(encoder_p, 42, self_p->time);
    pbtools_encoder_write_double(encoder_p, 41, self_p->altitude);
    pbtools_encoder_write_double(encoder_p, 40, self_p->longitude);
    pbtools_encoder_write_double(encoder_p, 39, self_p->latitude);
    pbtools_encoder_write_string(encoder_p, 38, self_p->vin_p);
    pbtools_encoder_write_string(encoder_p, 37, self_p->emuser_id_p);
    pbtools_encoder_write_uint32(encoder_p, 36, self_p->ble_debug_signal3);
    pbtools_encoder_write_uint32(encoder_p, 35, self_p->ble_debug_signal2);
    pbtools_encoder_write_uint32(encoder_p, 34, self_p->ble_debug_signal1);
    pbtools_encoder_write_uint32(encoder_p, 33, self_p->ble_debug_signal0);
    pbtools_encoder_write_uint32(encoder_p, 32, self_p->mcu_debug_signal3);
    pbtools_encoder_write_uint32(encoder_p, 31, self_p->mcu_debug_signal2);
    pbtools_encoder_write_uint32(encoder_p, 30, self_p->mcu_debug_signal1);
    pbtools_encoder_write_uint32(encoder_p, 29, self_p->mcu_debug_signal0);
    pbtools_encoder_write_bool(encoder_p, 28, self_p->motor_stall_fault);
    pbtools_encoder_write_bool(encoder_p, 27, self_p->controller_opamp_failure);
    pbtools_encoder_write_bool(encoder_p, 26, self_p->overvoltage_fault);
    pbtools_encoder_write_bool(encoder_p, 25, self_p->display_and_mcu_comm_failure);
    pbtools_encoder_write_bool(encoder_p, 24, self_p->battery_under_voltage_fault);
    pbtools_encoder_write_bool(encoder_p, 23, self_p->handle_bar_failure);
    pbtools_encoder_write_bool(encoder_p, 22, self_p->brake_failure);
    pbtools_encoder_write_bool(encoder_p, 21, self_p->motor_line_short_circuit_fault);
    pbtools_encoder_write_bool(encoder_p, 20, self_p->motor_hall_failure);
    pbtools_encoder_write_double(encoder_p, 19, self_p->vehicle_odo_reading);
    pbtools_encoder_write_bool(encoder_p, 18, self_p->walk_mode);
    pbtools_encoder_write_bool(encoder_p, 17, self_p->cruise_control);
    pbtools_encoder_write_bool(encoder_p, 16, self_p->brake);
    pbtools_encoder_write_bool(encoder_p, 15, self_p->headlamp);
    pbtools_encoder_write_bool(encoder_p, 14, self_p->side_stand);
    pbtools_encoder_write_uint32(encoder_p, 13, self_p->child_mode_speed_limit);
    pbtools_encoder_write_uint32(encoder_p, 12, self_p->current_trip_max_speed);
    pbtools_encoder_write_double(encoder_p, 11, self_p->current_trip_distance);
    pbtools_encoder_write_uint32(encoder_p, 10, self_p->calories);
    pbtools_encoder_write_uint32(encoder_p, 9, self_p->distance_to_empty);
    pbtools_encoder_write_enum(encoder_p, 8, self_p->eng_mode);
    pbtools_encoder_write_uint32(encoder_p, 7, self_p->pas);
    pbtools_encoder_write_bool(encoder_p, 6, self_p->throttle_cut_off);
    pbtools_encoder_write_uint32(encoder_p, 5, self_p->throttle);
    pbtools_encoder_write_uint32(encoder_p, 4, self_p->soc);
    pbtools_encoder_write_uint32(encoder_p, 3, self_p->battery_voltage);
    pbtools_encoder_write_uint32(encoder_p, 2, self_p->motor_speed);
    pbtools_encoder_write_uint32(encoder_p, 1, self_p->vehicle_speed);
}

void com_emotorad_backend_aggregation_flink_data_bike_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct com_emotorad_backend_aggregation_flink_data_bike_t *self_p)
{
    int wire_type;

    while (pbtools_decoder_available(decoder_p))
    {
        switch (pbtools_decoder_read_tag(decoder_p, &wire_type))
        {

        case 1:
            self_p->vehicle_speed = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 2:
            self_p->motor_speed = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 3:
            self_p->battery_voltage = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 4:
            self_p->soc = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 5:
            self_p->throttle = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 6:
            self_p->throttle_cut_off = pbtools_decoder_read_bool(decoder_p, wire_type);
            break;

        case 7:
            self_p->pas = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 8:
            self_p->eng_mode = pbtools_decoder_read_enum(decoder_p, wire_type);
            break;

        case 9:
            self_p->distance_to_empty = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 10:
            self_p->calories = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 11:
            self_p->current_trip_distance = pbtools_decoder_read_double(decoder_p, wire_type);
            break;

        case 12:
            self_p->current_trip_max_speed = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 13:
            self_p->child_mode_speed_limit = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 14:
            self_p->side_stand = pbtools_decoder_read_bool(decoder_p, wire_type);
            break;

        case 15:
            self_p->headlamp = pbtools_decoder_read_bool(decoder_p, wire_type);
            break;

        case 16:
            self_p->brake = pbtools_decoder_read_bool(decoder_p, wire_type);
            break;

        case 17:
            self_p->cruise_control = pbtools_decoder_read_bool(decoder_p, wire_type);
            break;

        case 18:
            self_p->walk_mode = pbtools_decoder_read_bool(decoder_p, wire_type);
            break;

        case 19:
            self_p->vehicle_odo_reading = pbtools_decoder_read_double(decoder_p, wire_type);
            break;

        case 20:
            self_p->motor_hall_failure = pbtools_decoder_read_bool(decoder_p, wire_type);
            break;

        case 21:
            self_p->motor_line_short_circuit_fault = pbtools_decoder_read_bool(decoder_p, wire_type);
            break;

        case 22:
            self_p->brake_failure = pbtools_decoder_read_bool(decoder_p, wire_type);
            break;

        case 23:
            self_p->handle_bar_failure = pbtools_decoder_read_bool(decoder_p, wire_type);
            break;

        case 24:
            self_p->battery_under_voltage_fault = pbtools_decoder_read_bool(decoder_p, wire_type);
            break;

        case 25:
            self_p->display_and_mcu_comm_failure = pbtools_decoder_read_bool(decoder_p, wire_type);
            break;

        case 26:
            self_p->overvoltage_fault = pbtools_decoder_read_bool(decoder_p, wire_type);
            break;

        case 27:
            self_p->controller_opamp_failure = pbtools_decoder_read_bool(decoder_p, wire_type);
            break;

        case 28:
            self_p->motor_stall_fault = pbtools_decoder_read_bool(decoder_p, wire_type);
            break;

        case 29:
            self_p->mcu_debug_signal0 = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 30:
            self_p->mcu_debug_signal1 = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 31:
            self_p->mcu_debug_signal2 = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 32:
            self_p->mcu_debug_signal3 = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 33:
            self_p->ble_debug_signal0 = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 34:
            self_p->ble_debug_signal1 = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 35:
            self_p->ble_debug_signal2 = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 36:
            self_p->ble_debug_signal3 = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 37:
            pbtools_decoder_read_string(decoder_p, wire_type, &self_p->emuser_id_p);
            break;

        case 38:
            pbtools_decoder_read_string(decoder_p, wire_type, &self_p->vin_p);
            break;

        case 39:
            self_p->latitude = pbtools_decoder_read_double(decoder_p, wire_type);
            break;

        case 40:
            self_p->longitude = pbtools_decoder_read_double(decoder_p, wire_type);
            break;

        case 41:
            self_p->altitude = pbtools_decoder_read_double(decoder_p, wire_type);
            break;

        case 42:
            self_p->time = pbtools_decoder_read_uint64(decoder_p, wire_type);
            break;

        default:
            pbtools_decoder_skip_field(decoder_p, wire_type);
            break;
        }
    }
}

void com_emotorad_backend_aggregation_flink_data_bike_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct com_emotorad_backend_aggregation_flink_data_bike_repeated_t *repeated_p)
{
    pbtools_encode_repeated_inner(
        encoder_p,
        field_number,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct com_emotorad_backend_aggregation_flink_data_bike_t),
        (pbtools_message_encode_inner_t)com_emotorad_backend_aggregation_flink_data_bike_encode_inner);
}

void com_emotorad_backend_aggregation_flink_data_bike_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct com_emotorad_backend_aggregation_flink_data_bike_repeated_t *repeated_p)
{
    pbtools_decode_repeated_inner(
        decoder_p,
        repeated_info_p,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct com_emotorad_backend_aggregation_flink_data_bike_t),
        (pbtools_message_init_t)com_emotorad_backend_aggregation_flink_data_bike_init,
        (pbtools_message_decode_inner_t)com_emotorad_backend_aggregation_flink_data_bike_decode_inner);
}

struct com_emotorad_backend_aggregation_flink_data_bike_t *
com_emotorad_backend_aggregation_flink_data_bike_new(
    void *workspace_p,
    size_t size)
{
    return (pbtools_message_new(
        workspace_p,
        size,
        sizeof(struct com_emotorad_backend_aggregation_flink_data_bike_t),
        (pbtools_message_init_t)com_emotorad_backend_aggregation_flink_data_bike_init));
}

int com_emotorad_backend_aggregation_flink_data_bike_encode(
    struct com_emotorad_backend_aggregation_flink_data_bike_t *self_p,
    uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_encode(
        &self_p->base,
        encoded_p,
        size,
        (pbtools_message_encode_inner_t)com_emotorad_backend_aggregation_flink_data_bike_encode_inner));
}

int com_emotorad_backend_aggregation_flink_data_bike_decode(
    struct com_emotorad_backend_aggregation_flink_data_bike_t *self_p,
    const uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_decode(
        &self_p->base,
        encoded_p,
        size,
        (pbtools_message_decode_inner_t)com_emotorad_backend_aggregation_flink_data_bike_decode_inner));
}

/***********************************Trip 1 message details *************************************************************/

void com_emotorad_backend_aggregation_flink_data_trip1_init(
    struct com_emotorad_backend_aggregation_flink_data_trip1_t *self_p,
    struct pbtools_heap_t *heap_p)
{
    self_p->base.heap_p = heap_p;
    self_p->max_speed = 33;
    self_p->trip_distance = 358;
    self_p->trip_duration = 332;
    self_p->average_speed = 19;
    self_p->motor_on_duration = 22;
    self_p->trip_power = 22;
    self_p->start_soc = 90;
    self_p->end_soc = 35;
    self_p->emuser_id_p = "0b927d97-782a-4c82-b9d2-e4e06774ed37"; // 0b927d97-782a-4c82-b9d2-e4e06774ed37
    self_p->vin_p = "Indian User";
    self_p->time = 910284540491034169;
}

void com_emotorad_backend_aggregation_flink_data_trip1_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct com_emotorad_backend_aggregation_flink_data_trip1_t *self_p)
{
    pbtools_encoder_write_uint64(encoder_p, 11, self_p->time);
    pbtools_encoder_write_string(encoder_p, 10, self_p->vin_p);
    pbtools_encoder_write_string(encoder_p, 9, self_p->emuser_id_p);
    pbtools_encoder_write_uint32(encoder_p, 8, self_p->end_soc);
    pbtools_encoder_write_uint32(encoder_p, 7, self_p->start_soc);
    pbtools_encoder_write_uint32(encoder_p, 6, self_p->trip_power);
    pbtools_encoder_write_uint32(encoder_p, 5, self_p->motor_on_duration);
    pbtools_encoder_write_uint32(encoder_p, 4, self_p->average_speed);
    pbtools_encoder_write_uint32(encoder_p, 3, self_p->trip_duration);
    pbtools_encoder_write_uint32(encoder_p, 2, self_p->trip_distance);
    pbtools_encoder_write_uint32(encoder_p, 1, self_p->max_speed);
}

void com_emotorad_backend_aggregation_flink_data_trip1_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct com_emotorad_backend_aggregation_flink_data_trip1_t *self_p)
{
    int wire_type;

    while (pbtools_decoder_available(decoder_p))
    {
        switch (pbtools_decoder_read_tag(decoder_p, &wire_type))
        {

        case 1:
            self_p->max_speed = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 2:
            self_p->trip_distance = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 3:
            self_p->trip_duration = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 4:
            self_p->average_speed = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 5:
            self_p->motor_on_duration = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 6:
            self_p->trip_power = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 7:
            self_p->start_soc = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 8:
            self_p->end_soc = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 9:
            pbtools_decoder_read_string(decoder_p, wire_type, &self_p->emuser_id_p);
            break;

        case 10:
            pbtools_decoder_read_string(decoder_p, wire_type, &self_p->vin_p);
            break;

        case 11:
            self_p->time = pbtools_decoder_read_uint64(decoder_p, wire_type);
            break;

        default:
            pbtools_decoder_skip_field(decoder_p, wire_type);
            break;
        }
    }
}

void com_emotorad_backend_aggregation_flink_data_trip1_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct com_emotorad_backend_aggregation_flink_data_trip1_repeated_t *repeated_p)
{
    pbtools_encode_repeated_inner(
        encoder_p,
        field_number,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct com_emotorad_backend_aggregation_flink_data_trip1_t),
        (pbtools_message_encode_inner_t)com_emotorad_backend_aggregation_flink_data_trip1_encode_inner);
}

void com_emotorad_backend_aggregation_flink_data_trip1_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct com_emotorad_backend_aggregation_flink_data_trip1_repeated_t *repeated_p)
{
    pbtools_decode_repeated_inner(
        decoder_p,
        repeated_info_p,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct com_emotorad_backend_aggregation_flink_data_trip1_t),
        (pbtools_message_init_t)com_emotorad_backend_aggregation_flink_data_trip1_init,
        (pbtools_message_decode_inner_t)com_emotorad_backend_aggregation_flink_data_trip1_decode_inner);
}

struct com_emotorad_backend_aggregation_flink_data_trip1_t *
com_emotorad_backend_aggregation_flink_data_trip1_new(
    void *workspace_p,
    size_t size)
{
    return (pbtools_message_new(
        workspace_p,
        size,
        sizeof(struct com_emotorad_backend_aggregation_flink_data_trip1_t),
        (pbtools_message_init_t)com_emotorad_backend_aggregation_flink_data_trip1_init));
}

int com_emotorad_backend_aggregation_flink_data_trip1_encode(
    struct com_emotorad_backend_aggregation_flink_data_trip1_t *self_p,
    uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_encode(
        &self_p->base,
        encoded_p,
        size,
        (pbtools_message_encode_inner_t)com_emotorad_backend_aggregation_flink_data_trip1_encode_inner));
}

int com_emotorad_backend_aggregation_flink_data_trip1_decode(
    struct com_emotorad_backend_aggregation_flink_data_trip1_t *self_p,
    const uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_decode(
        &self_p->base,
        encoded_p,
        size,
        (pbtools_message_decode_inner_t)com_emotorad_backend_aggregation_flink_data_trip1_decode_inner));
}

/***********************************Trip 2 message details *************************************************************/

void com_emotorad_backend_aggregation_flink_data_trip2_init(
    struct com_emotorad_backend_aggregation_flink_data_trip2_t *self_p,
    struct pbtools_heap_t *heap_p)
{
    self_p->base.heap_p = heap_p;
    self_p->eco_duration = 20;
    self_p->urban_duration = 316;
    self_p->lab_duration = 332;
    self_p->fitness_duration = 23;
    self_p->emuser_id_p = "0b927d97-782a-4c82-b9d2-e4e06774ed37";
    self_p->vin_p = "Indian User";
    self_p->time = 1140809326210294872;
}

void com_emotorad_backend_aggregation_flink_data_trip2_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct com_emotorad_backend_aggregation_flink_data_trip2_t *self_p)
{
    pbtools_encoder_write_uint64(encoder_p, 7, self_p->time);
    pbtools_encoder_write_string(encoder_p, 6, self_p->vin_p);
    pbtools_encoder_write_string(encoder_p, 5, self_p->emuser_id_p);
    pbtools_encoder_write_uint32(encoder_p, 4, self_p->fitness_duration);
    pbtools_encoder_write_uint32(encoder_p, 3, self_p->lab_duration);
    pbtools_encoder_write_uint32(encoder_p, 2, self_p->urban_duration);
    pbtools_encoder_write_uint32(encoder_p, 1, self_p->eco_duration);
}

void com_emotorad_backend_aggregation_flink_data_trip2_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct com_emotorad_backend_aggregation_flink_data_trip2_t *self_p)
{
    int wire_type;

    while (pbtools_decoder_available(decoder_p))
    {
        switch (pbtools_decoder_read_tag(decoder_p, &wire_type))
        {

        case 1:
            self_p->eco_duration = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 2:
            self_p->urban_duration = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 3:
            self_p->lab_duration = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 4:
            self_p->fitness_duration = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 5:
            pbtools_decoder_read_string(decoder_p, wire_type, &self_p->emuser_id_p);
            break;

        case 6:
            pbtools_decoder_read_string(decoder_p, wire_type, &self_p->vin_p);
            break;

        case 7:
            self_p->time = pbtools_decoder_read_uint64(decoder_p, wire_type);
            break;

        default:
            pbtools_decoder_skip_field(decoder_p, wire_type);
            break;
        }
    }
}

void com_emotorad_backend_aggregation_flink_data_trip2_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct com_emotorad_backend_aggregation_flink_data_trip2_repeated_t *repeated_p)
{
    pbtools_encode_repeated_inner(
        encoder_p,
        field_number,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct com_emotorad_backend_aggregation_flink_data_trip2_t),
        (pbtools_message_encode_inner_t)com_emotorad_backend_aggregation_flink_data_trip2_encode_inner);
}

void com_emotorad_backend_aggregation_flink_data_trip2_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct com_emotorad_backend_aggregation_flink_data_trip2_repeated_t *repeated_p)
{
    pbtools_decode_repeated_inner(
        decoder_p,
        repeated_info_p,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct com_emotorad_backend_aggregation_flink_data_trip2_t),
        (pbtools_message_init_t)com_emotorad_backend_aggregation_flink_data_trip2_init,
        (pbtools_message_decode_inner_t)com_emotorad_backend_aggregation_flink_data_trip2_decode_inner);
}

struct com_emotorad_backend_aggregation_flink_data_trip2_t *
com_emotorad_backend_aggregation_flink_data_trip2_new(
    void *workspace_p,
    size_t size)
{
    return (pbtools_message_new(
        workspace_p,
        size,
        sizeof(struct com_emotorad_backend_aggregation_flink_data_trip2_t),
        (pbtools_message_init_t)com_emotorad_backend_aggregation_flink_data_trip2_init));
}

int com_emotorad_backend_aggregation_flink_data_trip2_encode(
    struct com_emotorad_backend_aggregation_flink_data_trip2_t *self_p,
    uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_encode(
        &self_p->base,
        encoded_p,
        size,
        (pbtools_message_encode_inner_t)com_emotorad_backend_aggregation_flink_data_trip2_encode_inner));
}

int com_emotorad_backend_aggregation_flink_data_trip2_decode(
    struct com_emotorad_backend_aggregation_flink_data_trip2_t *self_p,
    const uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_decode(
        &self_p->base,
        encoded_p,
        size,
        (pbtools_message_decode_inner_t)com_emotorad_backend_aggregation_flink_data_trip2_decode_inner));
}

/***********************************End message details *************************************************************/

void com_emotorad_backend_aggregation_flink_data_end_init(
    struct com_emotorad_backend_aggregation_flink_data_end_t *self_p,
    struct pbtools_heap_t *heap_p)
{
    self_p->base.heap_p = heap_p;
    self_p->emuser_id_p = "0b927d97-782a-4c82-b9d2-e4e06774ed37";
    self_p->vin_p = "Indian User";
    self_p->time = 1721282408480;
}

void com_emotorad_backend_aggregation_flink_data_end_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct com_emotorad_backend_aggregation_flink_data_end_t *self_p)
{
    pbtools_encoder_write_uint64(encoder_p, 3, self_p->time);
    pbtools_encoder_write_string(encoder_p, 2, self_p->vin_p);
    pbtools_encoder_write_string(encoder_p, 1, self_p->emuser_id_p);
}

void com_emotorad_backend_aggregation_flink_data_end_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct com_emotorad_backend_aggregation_flink_data_end_t *self_p)
{
    int wire_type;

    while (pbtools_decoder_available(decoder_p))
    {
        switch (pbtools_decoder_read_tag(decoder_p, &wire_type))
        {

        case 1:
            pbtools_decoder_read_string(decoder_p, wire_type, &self_p->emuser_id_p);
            break;

        case 2:
            pbtools_decoder_read_string(decoder_p, wire_type, &self_p->vin_p);
            break;

        case 3:
            self_p->time = pbtools_decoder_read_uint64(decoder_p, wire_type);
            break;

        default:
            pbtools_decoder_skip_field(decoder_p, wire_type);
            break;
        }
    }
}

void com_emotorad_backend_aggregation_flink_data_end_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct com_emotorad_backend_aggregation_flink_data_end_repeated_t *repeated_p)
{
    pbtools_encode_repeated_inner(
        encoder_p,
        field_number,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct com_emotorad_backend_aggregation_flink_data_end_t),
        (pbtools_message_encode_inner_t)com_emotorad_backend_aggregation_flink_data_end_encode_inner);
}

void com_emotorad_backend_aggregation_flink_data_end_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct com_emotorad_backend_aggregation_flink_data_end_repeated_t *repeated_p)
{
    pbtools_decode_repeated_inner(
        decoder_p,
        repeated_info_p,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct com_emotorad_backend_aggregation_flink_data_end_t),
        (pbtools_message_init_t)com_emotorad_backend_aggregation_flink_data_end_init,
        (pbtools_message_decode_inner_t)com_emotorad_backend_aggregation_flink_data_end_decode_inner);
}

struct com_emotorad_backend_aggregation_flink_data_end_t *
com_emotorad_backend_aggregation_flink_data_end_new(
    void *workspace_p,
    size_t size)
{
    return (pbtools_message_new(
        workspace_p,
        size,
        sizeof(struct com_emotorad_backend_aggregation_flink_data_end_t),
        (pbtools_message_init_t)com_emotorad_backend_aggregation_flink_data_end_init));
}

int com_emotorad_backend_aggregation_flink_data_end_encode(
    struct com_emotorad_backend_aggregation_flink_data_end_t *self_p,
    uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_encode(
        &self_p->base,
        encoded_p,
        size,
        (pbtools_message_encode_inner_t)com_emotorad_backend_aggregation_flink_data_end_encode_inner));
}

int com_emotorad_backend_aggregation_flink_data_end_decode(
    struct com_emotorad_backend_aggregation_flink_data_end_t *self_p,
    const uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_decode(
        &self_p->base,
        encoded_p,
        size,
        (pbtools_message_decode_inner_t)com_emotorad_backend_aggregation_flink_data_end_decode_inner));
}
