#ifndef __PRIORITY_SYSTEM_H__
#define __PRIORITY_SYSTEM_H__

#ifndef PRI_GPS_TASK
#define PRI_GPS_TASK OSI_PRIORITY_ABOVE_NORMAL
#endif

#ifndef PRI_GPS_LOG_TASK
//#define PRI_GPS_LOG_TASK OSI_PRIORITY_LOW
#define PRI_GPS_LOG_TASK 7
#endif

#ifndef PRI_SPREADORBIT_SOONERFIX
#define PRI_SPREADORBIT_SOONERFIX OSI_PRIORITY_LOW
#endif

#ifndef PRI_SPREADORBIT_SAVEOBS
#define PRI_SPREADORBIT_SAVEOBS OSI_PRIORITY_LOW
#endif

#endif /*__PRIORITY_SYSTEM_H__*/
